spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KingJA/springconfig
          username: KingJA
          password: wzy1gqqbuu
